# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.TextField(default='jewellery'),
            preserve_default=False,
        ),
    ]
